"""
Website URL Ingestion Pipeline
Fetches content from the deployed Docusaurus textbook website, extracts clean text content,
chunks it, generates embeddings using Cohere, and stores them in Qdrant Cloud with rich metadata.
"""
import os
import logging
import requests
import cohere
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from qdrant_client import QdrantClient
from qdrant_client.http import models
from dotenv import load_dotenv
import xml.etree.ElementTree as ET
from typing import List, Dict, Any
import uuid
from datetime import datetime
import time
from dataclasses import dataclass
from typing import Optional


# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class ContentChunk:
    """A segment of extracted text from the textbook website with associated metadata"""
    chunk_id: str
    url: str
    module: str
    section: str
    content: str
    created_at: datetime
    updated_at: Optional[datetime] = None


@dataclass
class VectorEmbedding:
    """Numerical representation of content chunk generated by Cohere embedding models"""
    embedding_id: str
    vector: List[float]
    model: str
    created_at: datetime


@dataclass
class Metadata:
    """Structured information associated with each vector embedding"""
    chunk_id: str
    url: str
    module: str
    section: str
    source: str
    created_at: datetime


@dataclass
class PipelineConfiguration:
    """Settings that control the ingestion, processing, embedding, and storage operations"""
    pipeline_id: str
    sitemap_url: str
    chunk_size: int
    chunk_overlap: int
    embedding_model: str
    qdrant_collection: str
    last_run: Optional[datetime] = None
    status: str = "idle"


def setup_logging():
    """Implement logging configuration per research decisions"""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    logger = logging.getLogger(__name__)
    return logger


def load_environment_variables():
    """Create utility functions for environment variable loading"""
    cohere_api_key = os.getenv('COHERE_API_KEY')
    qdrant_url = os.getenv('QDRANT_URL')
    qdrant_api_key = os.getenv('QDRANT_API_KEY')
    sitemap_url = os.getenv('SITEMAP_URL', 'https://robotic-humanoid-book-nc39.vercel.app/sitemap.xml')

    if not cohere_api_key:
        raise ValueError("COHERE_API_KEY environment variable not set")
    if not qdrant_url:
        raise ValueError("QDRANT_URL environment variable not set")

    return {
        'cohere_api_key': cohere_api_key,
        'qdrant_url': qdrant_url,
        'qdrant_api_key': qdrant_api_key,
        'sitemap_url': sitemap_url
    }


def initialize_qdrant_client():
    """Implement Qdrant client initialization with error handling"""
    qdrant_url = os.getenv('QDRANT_URL')
    qdrant_api_key = os.getenv('QDRANT_API_KEY')

    if not qdrant_url:
        raise ValueError("QDRANT_URL environment variable not set")

    try:
        if qdrant_api_key:
            client = QdrantClient(url=qdrant_url, api_key=qdrant_api_key, timeout=10)
        else:
            client = QdrantClient(url=qdrant_url, timeout=10)

        # Test connection
        client.get_collections()
        logger.info("Successfully connected to Qdrant")
        return client
    except Exception as e:
        logger.error(f"Failed to connect to Qdrant: {e}")
        raise


def get_all_urls(sitemap_url: str) -> List[str]:
    """
    [US1] Implement get_all_urls function to fetch and parse sitemap.xml
    """
    try:
        response = requests.get(sitemap_url)
        response.raise_for_status()

        # Parse the sitemap XML
        root = ET.fromstring(response.content)

        # Extract URLs - handle both regular sitemaps and sitemap indexes
        urls = []
        for url_elem in root.findall('.//{http://www.sitemaps.org/schemas/sitemap/0.9}url/{http://www.sitemaps.org/schemas/sitemap/0.9}loc'):
            urls.append(url_elem.text.strip())

        logger.info(f"Found {len(urls)} URLs in sitemap")
        return urls
    except Exception as e:
        logger.error(f"Error fetching sitemap: {e}")
        raise


def validate_sitemap_url(sitemap_url: str) -> bool:
    """
    [US1] Add sitemap URL validation and error handling
    """
    try:
        # Basic URL format validation
        result = urlparse(sitemap_url)
        if not all([result.scheme, result.netloc]):
            logger.error(f"Invalid URL format: {sitemap_url}")
            return False

        # Test if the sitemap is accessible
        response = requests.head(sitemap_url, timeout=10)
        return response.status_code == 200
    except Exception as e:
        logger.error(f"Error validating sitemap URL {sitemap_url}: {e}")
        return False


def fetch_url_with_retry(url: str, max_retries: int = 3, timeout: int = 10) -> Optional[requests.Response]:
    """
    [US1] Implement URL fetching with retry logic and timeout handling
    """
    for attempt in range(max_retries):
        try:
            response = requests.get(url, timeout=timeout)
            if response.status_code == 200:
                return response
            elif response.status_code == 404:
                logger.warning(f"URL not found (404): {url}")
                return None  # Don't retry 404s
            else:
                logger.warning(f"HTTP {response.status_code} for {url} (attempt {attempt + 1}/{max_retries})")
        except requests.exceptions.Timeout:
            logger.warning(f"Timeout for {url} (attempt {attempt + 1}/{max_retries})")
        except requests.exceptions.RequestException as e:
            logger.warning(f"Request error for {url}: {e} (attempt {attempt + 1}/{max_retries})")

        if attempt < max_retries - 1:
            time.sleep(2 ** attempt)  # Exponential backoff

    logger.error(f"Failed to fetch {url} after {max_retries} attempts")
    return None


def extract_text_from_url(url: str) -> Dict[str, Any]:
    """
    [US2] Implement extract_text_from_url function with BeautifulSoup
    """
    try:
        response = fetch_url_with_retry(url)
        if not response:
            return {
                'url': url,
                'module': '',
                'section': '',
                'content': '',
                'title': ''
            }

        soup = BeautifulSoup(response.content, 'lxml')

        # [US2] Add HTML element removal for navigation, headers, footers, and non-content elements
        for element in soup(['nav', 'header', 'footer', 'aside', 'script', 'style', 'meta', 'link']):
            element.decompose()

        # [US2] Implement Docusaurus-specific CSS selector targeting for main content
        main_content = None
        for selector in ['.main-wrapper', '.container', 'main', '.docContent', '.markdown', '.theme-doc-markdown', '.container.padding-horiz--md']:
            main_content = soup.select_one(selector)
            if main_content:
                break

        # If no specific selector works, use body content
        if not main_content:
            main_content = soup.find('body')

        if main_content:
            # Remove any remaining non-content elements
            for element in main_content(['nav', 'header', 'footer', 'aside', 'script', 'style', 'meta', 'link']):
                element.decompose()

            text = main_content.get_text(separator=' ', strip=True)
        else:
            text = soup.get_text(separator=' ', strip=True)

        # [US2] Add module and section extraction from URL structure
        parsed_url = urlparse(url)
        path_parts = parsed_url.path.strip('/').split('/')

        module = path_parts[0] if path_parts and path_parts[0] else 'home'
        section = path_parts[1] if len(path_parts) > 1 else 'overview'

        return {
            'url': url,
            'module': module,
            'section': section,
            'content': text,
            'title': soup.title.string if soup.title else ''
        }
    except Exception as e:
        logger.error(f"Error extracting content from {url}: {e}")
        return {
            'url': url,
            'module': '',
            'section': '',
            'content': '',
            'title': ''
        }


def clean_content(content: str) -> str:
    """
    [US2] Create content validation and cleanup utilities
    """
    if not content:
        return ""

    # Remove extra whitespace
    import re
    content = re.sub(r'\s+', ' ', content)

    # Remove empty lines
    lines = [line.strip() for line in content.split('\n') if line.strip()]
    cleaned_content = '\n'.join(lines)

    return cleaned_content.strip()


def chunk_text(content: str, chunk_size: int = 1000, overlap: int = 200) -> List[Dict[str, Any]]:
    """
    [US3] Implement chunk_text function for fixed-size chunks with overlap
    """
    if not content:
        return []

    chunks = []
    start = 0

    while start < len(content):
        end = start + chunk_size

        # If this is not the last chunk, try to break at a sentence or word boundary
        if end < len(content):
            # Look for a good break point near the end
            temp_end = end
            while temp_end > start + chunk_size - overlap and temp_end < len(content):
                if content[temp_end] in '.!? \n':
                    end = temp_end + 1
                    break
                temp_end += 1

        chunk_text = content[start:end].strip()
        if chunk_text:  # Only add non-empty chunks
            chunk_id = str(uuid.uuid4())
            chunks.append({
                'chunk_id': chunk_id,
                'content': chunk_text,
                'start_pos': start,
                'end_pos': end
            })

        # Move start position with overlap
        start = end - overlap if end < len(content) else end

        # Prevent infinite loop if chunk_size is too small
        if start == end:
            start += chunk_size

    logger.info(f"Content chunked into {len(chunks)} pieces")
    return chunks


def initialize_cohere_client():
    """
    [US3] Implement Cohere client initialization with API key handling
    """
    cohere_api_key = os.getenv('COHERE_API_KEY')
    if not cohere_api_key:
        raise ValueError("COHERE_API_KEY environment variable not set")

    try:
        co = cohere.Client(cohere_api_key)
        logger.info("Successfully initialized Cohere client")
        return co
    except Exception as e:
        logger.error(f"Failed to initialize Cohere client: {e}")
        raise


def embed(texts: List[str]) -> List[List[float]]:
    """
    [US3] Implement embed function to generate vector embeddings from text
    """
    cohere_api_key = os.getenv('COHERE_API_KEY')
    if not cohere_api_key:
        raise ValueError("COHERE_API_KEY environment variable not set")

    co = cohere.Client(cohere_api_key)

    try:
        response = co.embed(
            texts=texts,
            model=os.getenv('EMBEDDING_MODEL', 'embed-multilingual-v3.0'),  # Balanced cost/performance
            input_type="search_document"
        )

        return response.embeddings
    except Exception as e:
        logger.error(f"Error generating embeddings: {e}")
        raise


def create_qdrant_collection(client: QdrantClient, collection_name: str = "rag_embeddings"):
    """
    [US3] Create Qdrant collection named "rag_embeddings" with proper schema
    """
    try:
        # Check if collection already exists
        collections = client.get_collections()
        existing_collections = [c.name for c in collections.collections]

        if collection_name in existing_collections:
            logger.info(f"Collection '{collection_name}' already exists")
            return

        # Create new collection
        client.create_collection(
            collection_name=collection_name,
            vectors_config=models.VectorParams(
                size=1024,  # Cohere embed-multilingual-v3.0 returns 1024-dim vectors
                distance=models.Distance.COSINE
            )
        )

        logger.info(f"Created collection '{collection_name}' with 1024-dim vectors")
    except Exception as e:
        logger.error(f"Error creating collection: {e}")
        raise


def save_chunk_to_qdrant(client: QdrantClient, collection_name: str, chunk_data: Dict[str, Any], embedding: List[float]):
    """
    [US3] Implement save_chunk_to_qdrant function with upsert functionality
    """
    try:
        # Prepare the payload with metadata
        # [US3] Add rich metadata (module, section, URL, chunk ID) to stored embeddings
        payload = {
            'url': chunk_data['url'],
            'module': chunk_data['module'],
            'section': chunk_data['section'],
            'content': chunk_data['content'],
            'title': chunk_data.get('title', ''),
            'created_at': datetime.utcnow().isoformat()
        }

        # Prepare the point to insert
        point = models.PointStruct(
            id=chunk_data['chunk_id'],
            vector=embedding,
            payload=payload
        )

        # Upsert the point (insert or update if exists)
        client.upsert(
            collection_name=collection_name,
            points=[point]
        )

        logger.info(f"Saved chunk {chunk_data['chunk_id']} to Qdrant")
    except Exception as e:
        logger.error(f"Error saving chunk to Qdrant: {e}")
        raise


def create_pipeline_config() -> PipelineConfiguration:
    """
    [US6] Create Pipeline Configuration class with validation rules
    """
    return PipelineConfiguration(
        pipeline_id=str(uuid.uuid4()),
        sitemap_url=os.getenv('SITEMAP_URL', 'https://robotic-humanoid-book-nc39.vercel.app/sitemap.xml'),
        chunk_size=int(os.getenv('CHUNK_SIZE', '1000')),
        chunk_overlap=int(os.getenv('CHUNK_OVERLAP', '200')),
        embedding_model=os.getenv('EMBEDDING_MODEL', 'embed-multilingual-v3.0'),
        qdrant_collection='rag_embeddings',
        status='idle'
    )


def update_pipeline_status(config: PipelineConfiguration, status: str):
    """
    [US6] Implement pipeline state management and status tracking
    """
    config.status = status
    config.last_run = datetime.utcnow()
    logger.info(f"Pipeline status updated to: {status}")


def validate_config(config: PipelineConfiguration):
    """
    [US6] Create configuration validation for chunk size and overlap parameters
    """
    if config.chunk_size <= 0:
        raise ValueError(f"Chunk size must be positive, got {config.chunk_size}")
    if config.chunk_overlap < 0:
        raise ValueError(f"Chunk overlap cannot be negative, got {config.chunk_overlap}")
    if config.chunk_overlap >= config.chunk_size:
        raise ValueError(f"Chunk overlap ({config.chunk_overlap}) must be less than chunk size ({config.chunk_size})")
    if not config.sitemap_url:
        raise ValueError("Sitemap URL cannot be empty")

    logger.info("Configuration validation passed")


def batch_process_embeddings(texts: List[str], batch_size: int = 10) -> List[List[float]]:
    """
    [US3] Implement batch processing for embedding generation to respect API limits
    """
    all_embeddings = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]

        try:
            batch_embeddings = embed(batch_texts)
            all_embeddings.extend(batch_embeddings)
            logger.info(f"Processed batch {i//batch_size + 1}/{(len(texts)-1)//batch_size + 1}")
        except Exception as e:
            logger.error(f"Error processing batch {i//batch_size + 1}: {e}")
            # Return partial results or raise based on requirements
            raise

    return all_embeddings


def main():
    """
    [US6] Create main function to orchestrate the entire pipeline (Ingestion → Processing → Embedding → Storage)
    """
    logger.info("Starting website ingestion pipeline")

    # Load configuration
    config = create_pipeline_config()
    validate_config(config)
    update_pipeline_status(config, 'starting')

    try:
        # Initialize clients
        qdrant_client = initialize_qdrant_client()
        create_qdrant_collection(qdrant_client, config.qdrant_collection)

        update_pipeline_status(config, 'fetching_urls')

        # Step 1: Get all URLs from sitemap
        urls = get_all_urls(config.sitemap_url)
        if not urls:
            logger.error("No URLs found in sitemap")
            update_pipeline_status(config, 'failed')
            return

        update_pipeline_status(config, 'extracting_content')

        # Process each URL
        for i, url in enumerate(urls):
            logger.info(f"Processing URL {i+1}/{len(urls)}: {url}")

            # Step 2: Extract text from URL
            page_data = extract_text_from_url(url)
            if not page_data['content']:
                logger.warning(f"No content extracted from {url}")
                continue

            update_pipeline_status(config, 'chunking')

            # Step 3: Chunk the text
            chunks = chunk_text(page_data['content'], config.chunk_size, config.chunk_overlap)
            if not chunks:
                logger.warning(f"No chunks created from {url}")
                continue

            # Prepare texts for embedding
            texts_to_embed = [chunk['content'] for chunk in chunks]

            update_pipeline_status(config, 'embedding')

            # Step 4: Generate embeddings (in batches to respect API limits)
            try:
                embeddings = batch_process_embeddings(texts_to_embed)

                update_pipeline_status(config, 'storing')

                # Step 5: Save to Qdrant
                for chunk, embedding_vector in zip(chunks, embeddings):
                    # Add URL, module, and section info to chunk data
                    chunk_data = {
                        'chunk_id': chunk['chunk_id'],
                        'url': page_data['url'],
                        'module': page_data['module'],
                        'section': page_data['section'],
                        'content': chunk['content'],
                        'title': page_data['title']
                    }

                    save_chunk_to_qdrant(qdrant_client, config.qdrant_collection, chunk_data, embedding_vector)

            except Exception as e:
                logger.error(f"Error processing content from {url}: {e}")
                continue

        update_pipeline_status(config, 'completed')
        logger.info("Website ingestion pipeline completed successfully")

    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        update_pipeline_status(config, 'failed')
        raise


if __name__ == "__main__":
    main()